# Skip all aliases in lib files
zstyle ':omz:lib:*' aliases no

source $HOME/.local/share/cubasepp/config/common/cubasepp

export ZSH="$CUBASEPP_PLUGIN_PATH/oh-my-zsh"
ZSH_THEME="agnoster"

plugins=(
  git
  ruby
  rails
  tmux
  zsh-syntax-highlighting
  history-substring-search
  # zsh-autocomplete
)

source $HOME/.local/share/cubasepp/config/common/zsh
source $ZSH/oh-my-zsh.sh

bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

