# File system
alias ls='eza -lh --group-directories-first --icons=auto --hyperlink'
alias ll='ls'
alias lsa='ls -a'
alias lt='eza --tree --level=2 --long --icons=auto --git --hyperlink'
alias lta='lt -a'
alias ff="fzf --preview 'bat --style=numbers --color=always {}'"
alias fd='fdfind'
alias cd='z'

# Directories
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'


# Tools
alias vim='nvim'
alias g='git'
alias d='docker'
alias lzg='lazygit'
alias lzd='lazydocker'

alias dm='mkdir -p'
alias dr='rmdir'

# Git
# alias gcm='git commit -m'
# alias gcam='git commit -a -m'
# alias gcad='git commit -a --amend'
