#!/bin/bash

if [ ! -d "$CUBASEPP_PLUGIN_PATH/oh-my-zsh/" ]; then
  sh -c "ZSH=$CUBASEPP_PLUGIN_PATH/oh-my-zsh $(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh) --unattended"
  git clone --depth 1 -- https://github.com/marlonrichert/zsh-autocomplete.git "$CUBASEPP_PLUGIN_PATH/oh-my-zsh/plugins/zsh-autocomplete"
  git clone --depth 1 -- https://github.com/zsh-users/zsh-syntax-highlighting.git "$CUBASEPP_PLUGIN_PATH/oh-my-zsh/plugins/zsh-syntax-highlighting"
fi
